# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet
#markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Lieanu's Site.

description:  mumbo-jumbo
author:
    name:   lieanu
    email:  liuyue0310@gmail.com
    github: lieanu
    twitter: Mr_LiuYue
    pinterest: 
    linkedin: yue-liu/62/58a/722
    bio: M.Eng In Information Security!
    email_md5: c0321804fd3d6bb0f9a498e6a8d7a650 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
